# Generated by Django 2.0.3 on 2018-04-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybills', '0002_auto_20180409_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basdata',
            name='add_who',
            field=models.IntegerField(blank=True, null=True, verbose_name='添加人'),
        ),
    ]
