# Generated by Django 2.0.3 on 2018-04-09 02:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybills', '0003_auto_20180409_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDebt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('value', models.FloatField(verbose_name='总额')),
                ('refund_date', models.DateField(verbose_name='偿还日期')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='编辑日期')),
            ],
            options={
                'verbose_name': '欠款单',
                'verbose_name_plural': '欠款单',
                'db_table': 'bill_bus_debt',
            },
        ),
        migrations.AlterModelOptions(
            name='basdata',
            options={'verbose_name': '基础数据', 'verbose_name_plural': '基础数据'},
        ),
        migrations.RemoveField(
            model_name='basdata',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='basdata',
            name='edit_time',
        ),
        migrations.AddField(
            model_name='basdata',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basdata',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='编辑日期'),
        ),
        migrations.AddField(
            model_name='busdebt',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybills.BasData', verbose_name='状态'),
        ),
    ]
