# Generated by Django 2.0.3 on 2018-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybills', '0007_auto_20180409_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basdata',
            name='type_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类型描述'),
        ),
    ]
