# Generated by Django 2.0.3 on 2018-04-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybills', '0009_auto_20180409_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdebt',
            name='refund_date',
            field=models.DateField(blank=True, null=True, verbose_name='偿还日期'),
        ),
    ]
