# Generated by Django 2.0.3 on 2018-04-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybills', '0011_auto_20180409_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDebtRefund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总额')),
                ('refund_date', models.DateField(verbose_name='偿还日期')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='编辑日期')),
                ('debt', models.ForeignKey(limit_choices_to={'status__lte': 'DEBT_STATUS_B'}, on_delete=django.db.models.deletion.CASCADE, to='mybills.BusDebt', verbose_name='欠款项')),
            ],
            options={
                'verbose_name_plural': '还款单',
                'db_table': 'bill_bus_debt_refund',
                'verbose_name': '还款单',
            },
        ),
    ]
