# Generated by Django 2.0.3 on 2018-04-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybills', '0012_busdebtrefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdebtrefund',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybills.BusDebt', verbose_name='欠款项'),
        ),
    ]
