# Generated by Django 2.0.3 on 2018-04-10 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybills', '0013_auto_20180409_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusExpenseDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='金额')),
                ('expense_date', models.DateField(verbose_name='偿还日期')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='编辑日期')),
                ('type', models.ForeignKey(limit_choices_to={'type': 'EXPENSE'}, on_delete=django.db.models.deletion.CASCADE, to='mybills.BasData', verbose_name='消费类型')),
            ],
            options={
                'verbose_name': '消费明细',
                'db_table': 'bill_bus_expense_details',
                'verbose_name_plural': '消费明细',
            },
        ),
        migrations.AlterField(
            model_name='busdebtrefund',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='金额'),
        ),
    ]
